#!/bin/bash
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
APP_NAME=$(basename "$SELF_DIR")

function show_usage {
	echo "Parameters and options:"
	echo
	echo "    -f base-image-name"
	echo "        Mandatory. Builds the reverse proxy from 'base-image-name'."
	echo
	echo "    -h"
	echo "        Displays this help and exits."
	echo
}

BASE_IMAGE=""
while getopts ":hf:" opt; do
	case $opt in
	f)
		BASE_IMAGE=$OPTARG
		;;
	h)
		show_usage
		exit
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		show_usage
		exit 64
		;;
	:)
		echo "Option -$OPTARG requires an argument" >&2
		show_usage
		exit 64
		;;
	esac
done

if [ -z $BASE_IMAGE ]; then
	echo "Missing -f argument" >&2
	show_usage
	exit 64
fi

docker build --no-cache -t $APP_NAME --build-arg BASE_IMAGE=$BASE_IMAGE "$SELF_DIR"build-context
