#!/bin/bash
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_NAME=$(basename "$SELF_DIR")

function say_no {
	echo "no"
	exit
}

service docker status &>/dev/null || say_no

status=$(docker inspect -f='{{.State.Status}}' "$APP_NAME" 2>/dev/null)
[ "$status" == "running" ] && {
	echo "yes"
	exit
}

say_no
