#!/bin/bash
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
APP_NAME=$(basename "$SELF_DIR")

[ $(. "$SELF_DIR"is-running) == "yes" ] || {
	echo "Error: $APP_NAME is not running" >&2
	exit 1
}

. "$SELF_DIR"resolve-containers
docker exec $APP_NAME bash -c 'service apache2 reload'
