#!/bin/bash
SELF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
APP_NAME=$(basename "$SELF_DIR")

[ $(. "$SELF_DIR"/is-running) == "yes" ] || {
	docker inspect -f='{{.State.Status}}' "$APP_NAME" &>/dev/null
	[ $? -ne 0 ] && {
		echo "$APP_NAME is already stopped"
		exit
	}
}

docker stop $APP_NAME >/dev/null
docker rm -f $APP_NAME >/dev/null && {
	echo "$APP_NAME stopped"
	exit
}

echo "Error while trying to remove $APP_NAME container" >&2
exit 1
